[package]
name = "player"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
ekstensions = { path = "../../ekstensions" }
log = "0.4.21"
env_logger = "0.11.3"
transform = { path = "../transform" }
controls = { path = "../controls" }

[features]
extension = []
