[package]
name = "ekstensions-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = "2.0.60"
deluxe = "0.5.0"
toml = "0.8.13"

[lib]
proc-macro = true
