[package]
name = "kkraft"
version = "0.1.0"
authors = ["Saskapult <“kieransmith@gmail.com”>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Use some optimizations for all deps
[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.rapier3d]
opt-level = 3
[profile.release]
codegen-units = 1

[profile.dev]
debug = 1

[dependencies]
image = "0.24"
winit = "0.26.1"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13.1"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
anyhow = "1.0"
thiserror = "1.0.30"
tobj = "3.0"
nalgebra = "0.29.0"
#dashmap = "4.0.2"	# Concurrent hashmap
rand = "0.8.4"
rand_xoshiro = "0.6.0"
noise = "0.7.0"
poisson = "0.10.1"
serde = "1.0.132"
bincode = "1.3.3"
ron = "0.7.0"
rapier3d = "0.11.1"
#dot_vox = "4.1.0"	# .vox files
derivative = "2.2.0"	# Sometimes I like to exclude fields from derived traits of a struct, this helps me to do that
mlua = { version = "0.7.1", features = ["lua54", "vendored"] }
egui = "0.18.1"
epi = "0.16.0"
egui_wgpu_backend = "0.18.0"
egui_winit_platform = "0.15.0"
egui_extras = "0.18.0"
splines = { version = "4.0.3", features = ["serde"] }
rayon = "1.5.1"
# viuer = "0.6.1"
generational-arena = "0.2.8"
lz4_flex = "0.9.3"
lru = "0.7.8"
shipyard = "0.6.2"
enumflags2 = "0.7.5"
crossbeam-channel = "0.5.6"
wgpu-profiler = "0.9.0"
# profiling = { version = "1.0.6", features = ["profile-with-tracy"] }
