[package]
name = "ekstensions"
version = "0.1.0"
edition = "2021"

# [workspace] 
# members = [
# 	"eks",
# 	"extensions/*"
# ]

[dependencies]
anyhow = "1.0.82"
env_logger = "0.11.3"
libloading = "0.8.3"
log = "0.4.21"
toml = "0.8.12"
walkdir = "2.5.0"
eks = { path = "eks" }
