[package]
name = "controls"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
arrayvec = "0.7.4"
crossbeam-channel = "0.5.12"
ekstensions = { path = "../../ekstensions" }
enumflags2 = "0.7.9"
log = "0.4.21"
slotmap = "1.0.7"
winit = "0.29.15"
egui = "0.27.2"
